// src/routes/(auth)/signup/+page.svelte
<script lang="ts">
  import RegisterForm from "$organisms/RegisterForm.svelte";
  import type { PageData } from "./$types";

  export let data: PageData;
</script>

<div class="flex flex-col gap-12 h-full lg:(gap-72 w-1/2 pr-12)">
  <h1 class="text-accent2 font-bold text-5xl uppercase">Register</h1>

  <RegisterForm data={data.registerForm} />
</div>

// src/app/(auth)/signup/page.tsx
import { RegisterForm } from "@/components/organisms/RegisterForm";

export default function Signup() {
  return (
    <div className="flex flex-col gap-12 h-full lg:gap-72 lg:w-1/2 lg:pr-12">
      <h1 className="text-accent2 font-bold text-5xl uppercase">Sign Up</h1>

      <RegisterForm />
    </div>
  );
}
