// src/components/molecules/Input/Input.tsx
import * as React from "react";

import { cn } from "@/lib/utils";

export interface InputProps extends React.InputHTMLAttributes<HTMLInputElement> {}

const Input = React.forwardRef<HTMLInputElement, InputProps>(
  ({ className, type, ...props }, ref) => {
    return (
      <input
        type={type}
        className={cn(
          "h-10 min-w-[240px] rounded-md px-3 py-2 text-gray-700 border border-gray-200",
          className
        )}
        ref={ref}
        {...props}
      />
    );
  }
);
Input.displayName = "Input";

export { Input };

// src/components/atoms/Input/Input.svelte
<script lang="ts">
  import { cn } from "$lib/utils";

  export let value: unknown;
  export let fullWidth: boolean = false;
  export let placeholder = "";

  let className: string | undefined = undefined;
  export { className as class };
</script>

<input
  class={cn(
    "h-10 min-w-[240px] rounded-md px-3 py-2 text-gray-700 border border-gray-200",
    className
  )}
  class:w-full={fullWidth}
  {placeholder}
  bind:value
  on:blur
  on:change
  on:click
  on:focus
  on:keydown
  on:keypress
  on:keyup
  on:mouseover
  on:mouseenter
  on:mouseleave
  on:paste
  on:input
  {...$$restProps}
/>
